---
- hosts: localhost
  gather_facts: no
  vars:
    - target: "{{ target_host }}"
      default: "10.128.128.218"

  tasks:
    - add_host:
        name: "{{ target }}"
        groups: os_server


- name: Install Kaapana server dependencies
  hosts: os_server
  strategy: free
  remote_user: "{{ remote_username }}"

  tasks:
    - name: Set OpenStack hostname
      become: yes
      hostname:
        name: "vm-{{ inventory_hostname.split('.')[2] }}-{{ inventory_hostname.split('.')[3] }}.cloud.dkfz-heidelberg.de"
      when: inventory_hostname.split('.')[0] == "10"

    # - name: Download server_installation.sh file locally
    #   get_url: 
    #     url: https://raw.githubusercontent.com/kaapana/kaapana/develop/server-installation/server_installation.sh
    #     dest: "{{ lookup('env','HOME') }}/server_installation.sh" 
    #   delegate_to: 127.0.0.1

    - set_fact:
        server_script: "{{ lookup('env','HOME') }}/server_installation/server_installation.sh"
    
    - name: Run server dependencies install script on server
      become: yes
      script: "{{ server_script }}  --quiet"

    - name: Reboot machine...
      become: yes
      reboot:
          reboot_timeout: 120
