---
- hosts: localhost
  gather_facts: no
  vars:
    - target: "{{ target_host }}"
      default: "10.128.128.218"

  tasks:
    - add_host:
        name: "{{ target }}"
        groups: os_server

- name: Install Kaapana platform on server
  hosts: os_server
  strategy: free
  remote_user: "{{ remote_username }}"

  tasks:
    # - name: Download install_platform.sh file
    #   get_url: 
    #     url: https://raw.githubusercontent.com/kaapana/kaapana/develop/platforms/kaapana-platform/platform-installation/install_platform.sh
    #     dest: "{{ lookup('env','HOME') }}/install_platform.sh"
    #   delegate_to: 127.0.0.1

    - set_fact:
        install_script: "{{ lookup('env','HOME') }}/kaapana/platforms/kaapana-platform/platform-installation/install_platform.sh"

    - name: Add container registry URL to install script
      replace:
        path: "{{ install_script }}"
        regexp: '^CONTAINER_REGISTRY_URL="[a-zA-Z./\-_]*"'
        replace: 'CONTAINER_REGISTRY_URL="{{ registry_url }}"'
      delegate_to: 127.0.0.1
    
    - name: Run platform install script
      become: no
      environment:
        TERM: xterm
      script: "{{ install_script }} --quiet --username {{ registry_user }} --password {{ registry_pwd }}"
