---
- name: delete a compute instance
  hosts: localhost
  gather_facts: false

  environment:
    OS_IDENTITY_API_VERSION: 2
    OS_ENDPOINT_TYPE: publicURL
  tasks:
    - name: Check if all required variables are passed using --extra-vars
      fail:
        msg: "variable {{ item }} not defined"
      when: item is not defined
      with_items:
        - "{{ os_project_id }}"
        - "{{ os_project_name }}"
        - "{{ os_username }}"
        - "{{ os_password }}"
        - "{{ os_instance_name }}"

    # - name: Get password from env...
    #   set_fact:
    #     password: "{{ lookup('env','CI_PASSWORD') or password }}"
    #   when: username == "jip-ci-kaapana" and password | length == 0
    
    - name: delete an instance
      environment: 
        OS_TENANT_ID: "{{ os_project_id }}"
      os_server:
        state: absent
        auth:
          auth_url: "https://cloud.dkfz-heidelberg.de:13000"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          user_domain_name: "AD"
          project_name: "{{ os_project_name }}"
        name: "{{ os_instance_name }}"
        timeout: 120
      register: del_instance

    - name: RESULT
      debug:
        msg: "INSTANCE DELETED SUCCESSFULLY"
    
    - name: RETURN
      debug:
        msg: "OK"
