---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: landingpage
  namespace: {{ .Values.global.base_namespace }}
  labels:
    k8s-app: landingpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: landingpage
  template:
    metadata:
      labels:
        app-name: landingpage
    spec:
      containers:
      - name: landingpage
        image: {{  .Values.global.registry_url }}/landing-page-racoon:0.1.3-vdev
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        ports:
        - name: landing-http
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: landing-http
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            memory: 10Mi
          limits:
            memory: 10Mi
        volumeMounts:
          - name: common-data-file
            mountPath: /app/jsons
      volumes:
      - name: common-data-file
        configMap:
          name: landing-page-config
      imagePullSecrets:
      - name: registry-secret
